<?php

use PHPUnit\Framework\TestCase;
use Creational\Pool\CarPool\Car;
use Creational\Pool\CarPool\CarPool;


class CarPoolTest extends TestCase
{
    private $carPool;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->carPool = new CarPool();
    }

    public function testCanRentCar()
    {
        $myCar = $this->carPool->rentCar();
        $myCar2 = $this->carPool->rentCar();

        $this->assertInstanceOf(Car::class, $myCar);

        $this->assertEquals(1, $this->carPool->getReport());
    }

    public function testCanFreeCar()
    {
        $myCar = $this->carPool->rentCar();
        $myCar2 = $this->carPool->rentCar();
        $this->carPool->freeCar($myCar);

        $this->assertEquals(2, $this->carPool->getReport());
        $this->assertEquals(1, $this->carPool->getfree());
    }

}